### ISSUE TITLE
scrapli and cygwin

### ISSUE THREAD

**Issue by slogo-heinzy** [scrapli/scrapli_netconf#2]
Hi There. I am a newbie, and trying to run Scrapli on cygwin/ windows 7.

i ran the commands within the cygwin window in the python interpreter :  

i imported the driver, created a device and ran the command
conn = IOSXEDriver(**device)

and received an exception error: UnsupportedPlatform: 'system' transport is not supported on **`Windows`**.please use a different transport

i understood that scrapli would work ok within cygwin?

many thanks

**Comment by carlmontanari** [comment]
Hey there @slogo-heinzy 

Oh this is interesting :) I don't have any windows machines so I never tested this out.... I *think* scrapli should work nicely on cygwin/wsl... I did *not* think about the fact that the `sys.platform` would still likely report windows as the platform version when using cygwin!

A quick test to get you going could be to use the `paramiko` or `ssh2` transports, then I can investigate cygwin support a little bit more. You can set the transport like so:

```
conn = IOSXEDriver(**device, transport="paramiko")
```

That should get you going for now (and *should* also work on "regular" windows AFAIK)... In the meantime can you check out this stack overflow issue: https://stackoverflow.com/questions/10597284/install-python-and-make-in-cygwin

I wonder if `python` on your cygwin shell is actually installed as linux python in cygwin or if it is "falling back" to the windows installed python version. Another thing that would be helpful for me would be if you could jump into python from cygwin -- just `python` at the shell should drop you into the repl, and then do: `import sys; print(sys.platform)` -- that will let us know what platform python thinks its running on.


Carl

**Comment by slogo-heinzy** [comment]
Hi Carl

Yes Scrapli Core

output from requested command:

>>> import sys; print(sys.platform)
win32


using your suggestion to use paramki /ssh2 transport method, i  now can enter command successfully 
conn = IOSXEDriver(**device, transport="paramiko")


but now get a different error when trying to open the connection: conn.open()

scrapli.exceptions.KeyVerificationFailed: x.x.x.x not in known_hosts!     ( i replaced ip real address with x.x.x.x )

Many thanks

**Comment by slogo-heinzy** [comment]
Hi Carl

Yes Scrapli core - Apologies for posting in wrong repo

using alternative transport method worked ok

output from command:
>>> import sys; print(sys.platform)
win32

Many thanks - i will investigate further...

**Comment by carlmontanari** [comment]
@slogo-heinzy no worries! Glad the other transports are working as expected!

FYI, booted a quick test windows VM and installed cygwin ++ python3.8 (from the cygwin installer) and it shows up as a platform of `cygwin` -- so I *think* that you should be able to download the cygwin installer, find the python3.8 interpreter and install that, then `python3.8` *should* be the cygwin installed one and *should* work. I tested and python3.8 actually works and runs a script w/ system but there may be some other issue I will check into later (think I just have a flubbed user/password somewhere, and also you will need to enable `comms_ansi` as it seems cygwin prints lots of ansi characters to the terminal). In general though I have very little (zero) motivation to support windows, so I would recommend WSL (if cygwin is misbehaving I guess), so just a heads up!

For any non-bug type things like this (or for windows stuff since its not "technically" supported) the best place to go is networktocode slack where there is a scrapli channel you can join. You can join that slack workspace [here](https://networktocode.herokuapp.com) if you aren't already on there!

Carl
