### ISSUE TITLE
Scrapli Timeout due to sending netconf 1.1 when 1.0 is set

### ISSUE THREAD

**Issue by kn-winter** [scrapli/scrapli_netconf#28]
Hello.  I'm looking to move some of my netconf scripts into scrapli and ran into an issue with my device.  It is a Siemens Ruggedcom switch so it is not part of the tested devices.

When I try to do anything (get config, sending rpc, etc.), it resulted in a timeout and there is no response from the switch after sending the rpc.  The hello message does work.  

The switch (server) supports both NETCONF 1.0 and NETCONF 1.1 and I notice the client hello sends NETCONF 1.1 back.  This is even after setting the netconf version to 1.0.
``` 
conn.netconf_version = NetconfVersion.VERSION_1_0
```

I attempted to manually modify the script to send a client hello with NETCONF version 1.0 capability and that generated the proper response from the switch although it still resulted in a timeout (most likely because my modification wasn't proper).

Is it possible to support NETCONF 1.0 style when the netconf version is set regardless of what the server says?

OS: CentOS 7.9
```
scrapli==2020.11.15 
scrapli-netconf==2020.11.15 
```

**Comment by carlmontanari** [comment]
Hey @kn-winter 

Currently, if the device advertises 1.1 capabilities we respond in the hello with only 1.1 capabilities. So the short answer is "no".

Is it possible your device will only advertise 1.0 capabilities if you connect on a different port? For example IOSXE seems to only advertise 1.0 capabilities if you connect on port 22, but advertises 1.0 and 1.1 if you connect on 830. I dunno if that is "normal"/or in any way standard but may be a quick fix to this.

Longer term (as this also came up somewhere else recently) I was planning to add a `prefer_1_0` option or something like that so you could force 1.0.... or test out if I can switch dynamically if I just respond to the server saying I will do 1.0 and 1.1 capabilities. I've never had any of that come up for me personally though so I have no idea if all the stuff I just wrote makes sense or will work :p 

I'd be open to a PR that could handle this request, otherwise its on my list but is really low priority so may be a while.

Carl

**Comment by kn-winter** [comment]
Hi Carl,

Thanks for responding.  I did try a different port and advertising multiple client capabilities but that didn't work.  Their documentation did specifically say to use the 1.0 prompt style even though the device advertise 1.1 capability.  I'll have to complain to them about it as I always advertise 1.0 so never had this problem before.

Once I finish testing moving all my scripts over to scrapli, I can look into seeing if I can add the prefer option.

Thanks,
Khiem

**Comment by carlmontanari** [comment]
One more point on this: setting the capability like: `conn.netconf_version = NetconfVersion.VERSION_1_0` is "right" but it won't do anything to prevent us from sending the 1.0 hello unfortunately. So if you wanted to test this out you would have to patch the "process open" method [here](https://github.com/scrapli/scrapli_netconf/blob/049b3723c469302a2ea33acd53a93f8c51e5b97c/scrapli_netconf/driver/base_driver.py#L58)

Will keep this open, to keep track of this as I def think this seems like a good feature to add/fix!

Thanks again!
Carl

**Comment by carlmontanari** [comment]
Tracking in #38 now
